version: '3'

services:
  mq:
    image: rabbitmq:3.5.6-management
    container_name: "rabbitmq-poc"
    expose:
      - "5672"
      - "15672"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

networks:
  network-backend:
    driver: bridge